import { IBM_Plex_Mono, Open_Sans } from 'next/font/google'
import './globals.css'
import Providers from '@/components/providers'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AuthWrapper from '@/components/AuthWrapper'

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // You can choose any needed weights
  variable: '--font-open-sans'
})

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500'], // Add the weights you plan to use
  variable: '--font-ibm-plex-mono'
})

export const metadata = {
  title: 'SkillSlate',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon.ico' type='image/x-icon' />
      </head>
      <body
        className={`${openSans.variable} ${ibmPlexMono.variable} antialiased scroll-smooth`}
      >
        <Providers>
          <Navbar />
          <AuthWrapper>{children}</AuthWrapper>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
